project_id = "dhyfbaptcprxxixgnpby"

[functions.analyze-closed-won]
verify_jwt = true

[functions.score-account]
verify_jwt = false

[functions.analyze-correlations]
verify_jwt = false

[functions.enrich-technology-insights]
verify_jwt = true

[functions.zapier-sync]
verify_jwt = true

[functions.analyze-firmographics]
verify_jwt = true

[functions.generate-api-key]
verify_jwt = true

[functions.generate-icp-recommendations]
verify_jwt = true

[functions.match-external-data]
verify_jwt = true

[functions.enrich-accounts]
verify_jwt = true

[functions.bulk-upload]
verify_jwt = true