project_id = "dhyfbaptcprxxixgnpby"

[functions.score-account]
verify_jwt = false

[functions.enrich-technology-insights]
verify_jwt = true

[functions.zapier-sync]
verify_jwt = true

[functions.generate-api-key]
verify_jwt = true