-- Step 1: Populate industry_mapping table with comprehensive mappings
INSERT INTO public.industry_mapping (raw_industry, zoominfo_primary, zoominfo_sub) VALUES
-- Software & Technology
('Software', 'Software', 'Computer Software'),
('Computer Software', 'Software', 'Computer Software'),
('Software Development', 'Software', 'Computer Software'),
('SaaS', 'Software', 'Computer Software'),
('Enterprise Software', 'Software', 'Computer Software'),
('Technology', 'Software', 'Computer Software'),
('Information Technology', 'Software', 'Computer Software'),
('IT', 'Software', 'Computer Software'),
('Tech', 'Software', 'Computer Software'),

-- Business Services
('Professional Services', 'Business Services', 'Management Consulting'),
('Consulting', 'Business Services', 'Management Consulting'),
('Management Consulting', 'Business Services', 'Management Consulting'),
('IT Services', 'Business Services', 'Custom Software & IT Services'),
('IT Services and IT Consulting', 'Business Services', 'Custom Software & IT Services'),
('IT Consulting', 'Business Services', 'Custom Software & IT Services'),
('Business Services', 'Business Services', 'Business Services - Other'),
('Staffing', 'Business Services', 'Staffing & Recruiting'),
('Staffing & Recruiting', 'Business Services', 'Staffing & Recruiting'),
('Staffing and Recruiting', 'Business Services', 'Staffing & Recruiting'),
('Human Resources', 'Business Services', 'Staffing & Recruiting'),
('HR Services', 'Business Services', 'Staffing & Recruiting'),
('Marketing Services', 'Business Services', 'Advertising & Marketing'),
('Marketing', 'Business Services', 'Advertising & Marketing'),
('Advertising', 'Business Services', 'Advertising & Marketing'),
('Advertising & Marketing', 'Business Services', 'Advertising & Marketing'),
('Public Relations', 'Business Services', 'Advertising & Marketing'),
('Research', 'Business Services', 'Research & Development'),
('Research & Development', 'Business Services', 'Research & Development'),
('Market Research', 'Business Services', 'Research & Development'),
('Outsourcing', 'Business Services', 'Business Process Outsourcing'),
('BPO', 'Business Services', 'Business Process Outsourcing'),
('Security Services', 'Business Services', 'Security Products & Services'),
('Security', 'Business Services', 'Security Products & Services'),

-- Finance
('Financial Services', 'Finance', 'Financial Services - Other'),
('Finance', 'Finance', 'Financial Services - Other'),
('Banking', 'Finance', 'Banking'),
('Investment Banking', 'Finance', 'Investment Banking'),
('Investment Management', 'Finance', 'Investment Banking'),
('Venture Capital', 'Finance', 'Venture Capital & Private Equity'),
('Private Equity', 'Finance', 'Venture Capital & Private Equity'),
('Venture Capital & Private Equity', 'Finance', 'Venture Capital & Private Equity'),
('Asset Management', 'Finance', 'Investment Banking'),
('Wealth Management', 'Finance', 'Investment Banking'),
('Credit Unions', 'Finance', 'Credit Unions'),
('Accounting', 'Finance', 'Accounting'),
('Accounting Services', 'Finance', 'Accounting'),

-- Manufacturing
('Manufacturing', 'Manufacturing', 'Manufacturing - Other'),
('Manufacturing - Non-Durables', 'Manufacturing', 'Manufacturing - Other'),
('Manufacturing - Durables', 'Manufacturing', 'Manufacturing - Other'),
('Industrial Manufacturing', 'Manufacturing', 'Industrial Machinery & Equipment'),
('Machinery', 'Manufacturing', 'Industrial Machinery & Equipment'),
('Industrial Machinery', 'Manufacturing', 'Industrial Machinery & Equipment'),
('Automotive', 'Manufacturing', 'Motor Vehicles'),
('Automotive Manufacturing', 'Manufacturing', 'Motor Vehicles'),
('Motor Vehicles', 'Manufacturing', 'Motor Vehicles'),
('Aerospace', 'Manufacturing', 'Aerospace & Defense'),
('Aerospace & Defense', 'Manufacturing', 'Aerospace & Defense'),
('Defense', 'Manufacturing', 'Aerospace & Defense'),
('Electronics', 'Manufacturing', 'Electronics'),
('Electronics Manufacturing', 'Manufacturing', 'Electronics'),
('Semiconductors', 'Manufacturing', 'Semiconductors'),
('Semiconductor', 'Manufacturing', 'Semiconductors'),
('Plastics', 'Manufacturing', 'Plastics & Rubber'),
('Plastics & Rubber', 'Manufacturing', 'Plastics & Rubber'),
('Chemicals', 'Manufacturing', 'Chemicals'),
('Chemical Manufacturing', 'Manufacturing', 'Chemicals'),
('Textiles', 'Manufacturing', 'Textiles'),
('Textile Manufacturing', 'Manufacturing', 'Textiles'),
('Paper & Forest Products', 'Manufacturing', 'Paper & Forest Products'),
('Paper Products', 'Manufacturing', 'Paper & Forest Products'),
('Food Production', 'Manufacturing', 'Food & Beverage Manufacturing'),
('Food & Beverage Manufacturing', 'Manufacturing', 'Food & Beverage Manufacturing'),
('Food Manufacturing', 'Manufacturing', 'Food & Beverage Manufacturing'),
('Beverage Manufacturing', 'Manufacturing', 'Food & Beverage Manufacturing'),

-- Healthcare
('Healthcare', 'Hospitals & Physicians Clinics', 'Hospitals'),
('Hospitals & Healthcare', 'Hospitals & Physicians Clinics', 'Hospitals'),
('Hospitals and Health Care', 'Hospitals & Physicians Clinics', 'Hospitals'),
('Hospitals', 'Hospitals & Physicians Clinics', 'Hospitals'),
('Hospital', 'Hospitals & Physicians Clinics', 'Hospitals'),
('Health Care', 'Hospitals & Physicians Clinics', 'Hospitals'),
('Medical', 'Hospitals & Physicians Clinics', 'Physicians Clinics'),
('Medical Practice', 'Hospitals & Physicians Clinics', 'Physicians Clinics'),
('Physicians', 'Hospitals & Physicians Clinics', 'Physicians Clinics'),
('Clinics', 'Hospitals & Physicians Clinics', 'Physicians Clinics'),
('Mental Health', 'Hospitals & Physicians Clinics', 'Hospitals'),
('Ambulatory Care', 'Hospitals & Physicians Clinics', 'Physicians Clinics'),

-- Insurance
('Insurance', 'Insurance', 'Insurance - Other'),
('Insurance Services', 'Insurance', 'Insurance - Other'),
('Life Insurance', 'Insurance', 'Life Insurance'),
('Health Insurance', 'Insurance', 'Health Insurance'),
('Property Insurance', 'Insurance', 'Property & Casualty Insurance'),
('Property & Casualty Insurance', 'Insurance', 'Property & Casualty Insurance'),
('Auto Insurance', 'Insurance', 'Property & Casualty Insurance'),

-- Retail
('Retail', 'Retail', 'Retail - Other'),
('Retail Trade', 'Retail', 'Retail - Other'),
('E-commerce', 'Retail', 'Internet & Mail-Order Retail'),
('Ecommerce', 'Retail', 'Internet & Mail-Order Retail'),
('Online Retail', 'Retail', 'Internet & Mail-Order Retail'),
('Consumer Goods', 'Retail', 'Retail - Other'),
('Consumer Products', 'Retail', 'Retail - Other'),
('Apparel', 'Retail', 'Apparel & Accessories Retail'),
('Apparel & Fashion', 'Retail', 'Apparel & Accessories Retail'),
('Fashion', 'Retail', 'Apparel & Accessories Retail'),
('Grocery', 'Retail', 'Food & Beverage Retail'),
('Food Retail', 'Retail', 'Food & Beverage Retail'),
('Supermarkets', 'Retail', 'Food & Beverage Retail'),

-- Education
('Education', 'Education', 'Education - Other'),
('Education Management', 'Education', 'Education - Other'),
('Education & Educational Institutions', 'Education', 'Education - Other'),
('Higher Education', 'Education', 'Colleges & Universities'),
('Colleges & Universities', 'Education', 'Colleges & Universities'),
('Universities', 'Education', 'Colleges & Universities'),
('K-12', 'Education', 'K-12 Schools'),
('K-12 Education', 'Education', 'K-12 Schools'),
('Primary Education', 'Education', 'K-12 Schools'),
('Secondary Education', 'Education', 'K-12 Schools'),
('E-Learning', 'Education', 'Education - Other'),
('EdTech', 'Education', 'Education - Other'),
('Training', 'Education', 'Education - Other'),

-- Government
('Government', 'Government', 'Government - Other'),
('Government Administration', 'Government', 'Government - Other'),
('State & Federal', 'Government', 'Government - Other'),
('Federal Government', 'Government', 'Federal'),
('State Government', 'Government', 'State'),
('Local Government', 'Government', 'Local'),
('Public Administration', 'Government', 'Government - Other'),
('Public Sector', 'Government', 'Government - Other'),
('Military', 'Government', 'Federal'),

-- Telecommunications
('Telecommunications', 'Telecommunications', 'Telecommunications - Other'),
('Telecom', 'Telecommunications', 'Telecommunications - Other'),
('Wireless', 'Telecommunications', 'Wireless Telecommunications'),
('Wireless Telecommunications', 'Telecommunications', 'Wireless Telecommunications'),
('Cable', 'Telecommunications', 'Cable & Satellite'),
('Cable & Satellite', 'Telecommunications', 'Cable & Satellite'),
('Internet Service Providers', 'Telecommunications', 'Telecommunications - Other'),
('ISP', 'Telecommunications', 'Telecommunications - Other'),

-- Energy, Utilities & Waste
('Energy', 'Energy, Utilities & Waste', 'Energy - Other'),
('Energy, Oil, & Utilities', 'Energy, Utilities & Waste', 'Energy - Other'),
('Oil & Gas', 'Energy, Utilities & Waste', 'Oil & Gas Exploration & Production'),
('Oil & Energy', 'Energy, Utilities & Waste', 'Oil & Gas Exploration & Production'),
('Oil and Gas', 'Energy, Utilities & Waste', 'Oil & Gas Exploration & Production'),
('Petroleum', 'Energy, Utilities & Waste', 'Oil & Gas Exploration & Production'),
('Utilities', 'Energy, Utilities & Waste', 'Utilities'),
('Electric Utilities', 'Energy, Utilities & Waste', 'Utilities'),
('Gas Utilities', 'Energy, Utilities & Waste', 'Utilities'),
('Water Utilities', 'Energy, Utilities & Waste', 'Utilities'),
('Renewable Energy', 'Energy, Utilities & Waste', 'Renewables & Environment'),
('Renewables', 'Energy, Utilities & Waste', 'Renewables & Environment'),
('Solar', 'Energy, Utilities & Waste', 'Renewables & Environment'),
('Wind Energy', 'Energy, Utilities & Waste', 'Renewables & Environment'),
('Clean Energy', 'Energy, Utilities & Waste', 'Renewables & Environment'),
('Waste Management', 'Energy, Utilities & Waste', 'Waste Treatment & Environmental Services'),
('Environmental Services', 'Energy, Utilities & Waste', 'Waste Treatment & Environmental Services'),

-- Real Estate
('Real Estate', 'Real Estate', 'Real Estate - Other'),
('Real Estate & Property Management', 'Real Estate', 'Real Estate - Other'),
('Commercial Real Estate', 'Real Estate', 'Commercial Real Estate'),
('Residential Real Estate', 'Real Estate', 'Residential Real Estate'),
('Property Management', 'Real Estate', 'Real Estate - Other'),
('REIT', 'Real Estate', 'Real Estate - Other'),
('Real Estate Investment', 'Real Estate', 'Real Estate - Other'),

-- Construction
('Construction', 'Construction', 'Construction - Other'),
('Building Construction', 'Construction', 'Construction - Other'),
('Civil Engineering', 'Construction', 'Engineering Services'),
('Architecture', 'Construction', 'Architecture & Planning'),
('Architecture & Planning', 'Construction', 'Architecture & Planning'),
('Engineering', 'Construction', 'Engineering Services'),
('Engineering Services', 'Construction', 'Engineering Services'),

-- Transportation
('Transportation', 'Transportation', 'Transportation - Other'),
('Logistics', 'Transportation', 'Freight & Logistics'),
('Logistics & Supply Chain', 'Transportation', 'Freight & Logistics'),
('Supply Chain', 'Transportation', 'Freight & Logistics'),
('Freight', 'Transportation', 'Freight & Logistics'),
('Trucking', 'Transportation', 'Trucking'),
('Shipping', 'Transportation', 'Freight & Logistics'),
('Airlines', 'Transportation', 'Airlines'),
('Aviation', 'Transportation', 'Airlines'),
('Railroads', 'Transportation', 'Railroads'),
('Rail', 'Transportation', 'Railroads'),
('Maritime', 'Transportation', 'Maritime'),

-- Media & Internet
('Media', 'Media & Internet', 'Media - Other'),
('Media & Entertainment', 'Media & Internet', 'Media - Other'),
('Entertainment', 'Media & Internet', 'Media - Other'),
('Publishing', 'Media & Internet', 'Publishing'),
('Broadcast Media', 'Media & Internet', 'Broadcasting'),
('Broadcasting', 'Media & Internet', 'Broadcasting'),
('Television', 'Media & Internet', 'Broadcasting'),
('Radio', 'Media & Internet', 'Broadcasting'),
('Internet', 'Media & Internet', 'Internet Software & Services'),
('Online Media', 'Media & Internet', 'Internet Software & Services'),
('Digital Media', 'Media & Internet', 'Internet Software & Services'),
('Social Media', 'Media & Internet', 'Social Networks'),
('Gaming', 'Media & Internet', 'Computer Games'),
('Video Games', 'Media & Internet', 'Computer Games'),
('Music', 'Media & Internet', 'Media - Other'),
('Film', 'Media & Internet', 'Media - Other'),
('Movies', 'Media & Internet', 'Media - Other'),

-- Law Firms & Legal Services
('Legal', 'Law Firms & Legal Services', 'Law Firms'),
('Legal Services', 'Law Firms & Legal Services', 'Law Firms'),
('Law Services', 'Law Firms & Legal Services', 'Law Firms'),
('Law Practice', 'Law Firms & Legal Services', 'Law Firms'),
('Law Firm', 'Law Firms & Legal Services', 'Law Firms'),
('Law Firms', 'Law Firms & Legal Services', 'Law Firms'),
('Attorney', 'Law Firms & Legal Services', 'Law Firms'),
('Attorneys', 'Law Firms & Legal Services', 'Law Firms'),

-- Consumer Services
('Consumer Services', 'Consumer Services', 'Consumer Services - Other'),
('Hospitality', 'Consumer Services', 'Hotels & Resorts'),
('Hotels', 'Consumer Services', 'Hotels & Resorts'),
('Hotels & Resorts', 'Consumer Services', 'Hotels & Resorts'),
('Lodging', 'Consumer Services', 'Hotels & Resorts'),
('Restaurants', 'Consumer Services', 'Restaurants'),
('Food & Beverage', 'Consumer Services', 'Restaurants'),
('Food Services', 'Consumer Services', 'Restaurants'),
('Travel', 'Consumer Services', 'Travel Agencies & Services'),
('Travel & Tourism', 'Consumer Services', 'Travel Agencies & Services'),
('Tourism', 'Consumer Services', 'Travel Agencies & Services'),
('Leisure', 'Consumer Services', 'Consumer Services - Other'),
('Recreation', 'Consumer Services', 'Consumer Services - Other'),
('Fitness', 'Consumer Services', 'Consumer Services - Other'),
('Personal Services', 'Consumer Services', 'Consumer Services - Other'),

-- Organizations (Non-Profit)
('Non-profit', 'Organizations', 'Non-Profit & Charitable Organizations'),
('Non-Profit', 'Organizations', 'Non-Profit & Charitable Organizations'),
('Nonprofit', 'Organizations', 'Non-Profit & Charitable Organizations'),
('Non-profit Organizations', 'Organizations', 'Non-Profit & Charitable Organizations'),
('Nonprofit Organization Management', 'Organizations', 'Non-Profit & Charitable Organizations'),
('Charity', 'Organizations', 'Non-Profit & Charitable Organizations'),
('Charitable', 'Organizations', 'Non-Profit & Charitable Organizations'),
('Foundation', 'Organizations', 'Non-Profit & Charitable Organizations'),
('Religious', 'Organizations', 'Religious Organizations'),
('Religious Organizations', 'Organizations', 'Religious Organizations'),
('Church', 'Organizations', 'Religious Organizations'),
('Trade Association', 'Organizations', 'Membership Organizations'),
('Association', 'Organizations', 'Membership Organizations'),
('Membership Organizations', 'Organizations', 'Membership Organizations'),

-- Agriculture
('Agriculture', 'Agriculture', 'Agriculture - Other'),
('Farming', 'Agriculture', 'Crop Production'),
('Crop Production', 'Agriculture', 'Crop Production'),
('Ranching', 'Agriculture', 'Animal Production'),
('Animal Production', 'Agriculture', 'Animal Production'),
('Livestock', 'Agriculture', 'Animal Production'),
('Forestry', 'Agriculture', 'Forestry & Logging'),
('Fishing', 'Agriculture', 'Fishing, Hunting & Trapping'),

-- Minerals & Mining
('Mining', 'Minerals & Mining', 'Mining - Other'),
('Mining & Metals', 'Minerals & Mining', 'Mining - Other'),
('Metals', 'Minerals & Mining', 'Mining - Other'),
('Coal Mining', 'Minerals & Mining', 'Coal Mining'),
('Metal Mining', 'Minerals & Mining', 'Metal Mining'),

-- Biotech & Pharmaceuticals
('Biotechnology', 'Biotech & Pharmaceuticals', 'Biotechnology'),
('Biotech', 'Biotech & Pharmaceuticals', 'Biotechnology'),
('Pharmaceuticals', 'Biotech & Pharmaceuticals', 'Pharmaceuticals'),
('Pharmaceutical', 'Biotech & Pharmaceuticals', 'Pharmaceuticals'),
('Pharma', 'Biotech & Pharmaceuticals', 'Pharmaceuticals'),
('Life Sciences', 'Biotech & Pharmaceuticals', 'Biotechnology'),
('Drug Manufacturing', 'Biotech & Pharmaceuticals', 'Pharmaceuticals'),

-- Medical Devices & Equipment
('Medical Devices', 'Medical Devices & Equipment', 'Medical Devices'),
('Medical Equipment', 'Medical Devices & Equipment', 'Medical Devices'),
('Medical Device', 'Medical Devices & Equipment', 'Medical Devices'),
('Health Care Equipment', 'Medical Devices & Equipment', 'Medical Devices'),
('Healthcare Equipment', 'Medical Devices & Equipment', 'Medical Devices'),
('Medical Technology', 'Medical Devices & Equipment', 'Medical Devices'),
('MedTech', 'Medical Devices & Equipment', 'Medical Devices'),

-- Hardware
('Hardware', 'Hardware', 'Hardware - Other'),
('Computer Hardware', 'Hardware', 'Computer Hardware'),
('Networking', 'Hardware', 'Communications Equipment'),
('Network Equipment', 'Hardware', 'Communications Equipment'),
('Communications Equipment', 'Hardware', 'Communications Equipment'),
('Storage', 'Hardware', 'Computer Hardware'),

-- Wholesale
('Wholesale', 'Wholesale', 'Wholesale - Other'),
('Wholesale Trade', 'Wholesale', 'Wholesale - Other'),
('Distribution', 'Wholesale', 'Wholesale - Other'),
('Distributor', 'Wholesale', 'Wholesale - Other')

ON CONFLICT (raw_industry) DO UPDATE SET
  zoominfo_primary = EXCLUDED.zoominfo_primary,
  zoominfo_sub = EXCLUDED.zoominfo_sub;