
-- Update existing ICP profile with comprehensive Seagate 2025 criteria
UPDATE public.icp_profiles
SET 
  name = 'Seagate 2025 ICP - Enterprise Technology & Data Infrastructure',
  description = 'Enterprise companies with 1,000+ employees in technology-intensive industries requiring data storage, cloud infrastructure, and IT modernization solutions. Focuses on companies with established IT departments, cloud migration initiatives, and data management needs.',
  use_case = 'Enterprise data infrastructure and cloud storage solutions',
  status = 'active',
  industries = ARRAY[
    'Technology',
    'Software',
    'Financial Services',
    'Healthcare',
    'Manufacturing',
    'Education',
    'Media & Entertainment',
    'Telecommunications',
    'Energy & Utilities',
    'Business Services'
  ],
  sub_industries = ARRAY[
    'Custom Software & IT Services',
    'Information & Document Management',
    'Research & Development',
    'Security Products & Services',
    'Colleges & Universities',
    'Oil & Gas Exploration & Services',
    'Waste Treatment',
    'Water Treatment',
    'Banking',
    'Credit Cards & Transaction Processing',
    'Investment Banking',
    'Lending & Brokerage',
    'Venture Capital & Private Equity',
    'Medical Laboratories & Imaging Centers',
    'Hospitals & Physicians Clinics',
    'Medical & Surgical Hospitals',
    'Aerospace & Defense',
    'Appliances',
    'Automotive Parts',
    'Computer Equipment & Peripherals',
    'Medical Devices & Equipment',
    'Pharmaceuticals',
    'Broadcasting',
    'Publishing',
    'Social Networks',
    'Data Collection & Internet Portals',
    'BI Software',
    'Content & Collaboration Software',
    'CRM Software',
    'Database & File Management Software',
    'ERP Software',
    'Healthcare Software',
    'Cable & Satellite',
    'Internet Service Providers',
    'Telephony & Wireless'
  ],
  company_sizes = ARRAY[1000, 2000, 5000, 10000],
  revenue_ranges = ARRAY[
    '$25M-$50M',
    '$50M-$100M',
    '$100M-$500M',
    '$500M-$1B',
    '$1B-$5B',
    '$5B+'
  ],
  geographies = ARRAY[
    'United States',
    'Canada',
    'United Kingdom',
    'Germany',
    'France',
    'Netherlands',
    'Australia',
    'Singapore',
    'Japan',
    'India'
  ],
  persona_job_titles = ARRAY[
    'CIO', 'CTO', 'Chief Architect', 'Chief Data Officer', 'CDO',
    'Head of IT', 'Head of Cloud', 'Head of Infrastructure',
    'VP of IT', 'VP of Engineering', 'VP of Technology',
    'VP of Cloud', 'VP of Infrastructure',
    'Cloud Infrastructure Engineer', 'Cloud Infrastructure Architect',
    'Cloud Solutions Architect', 'Cloud Platform Engineer',
    'Cloud Operations Engineer', 'Cloud Operations Manager',
    'Cloud Storage Product Manager',
    'AWS Architect', 'AWS Solutions Architect', 'AWS Engineer',
    'Azure Architect', 'Azure Solutions Architect', 'Azure Engineer',
    'Infrastructure Architect', 'Infrastructure Engineer',
    'Infrastructure Manager',
    'DevOps Engineer', 'DevOps Manager', 'DevOps Lead',
    'DevOps Architect', 'Site Reliability Engineer', 'SRE',
    'Data Architect', 'Data Engineer',
    'Database Administrator', 'Database Analyst', 'Database Manager',
    'Data Warehouse Architect', 'Data Warehouse Engineer',
    'Disaster Recovery Manager', 'Disaster Recovery Specialist',
    'Enterprise Architect',
    'IT Operations Manager', 'IT Operations Director',
    'Systems Administrator', 'Systems Engineer',
    'Network Administrator', 'Network Engineer',
    'Information Manager',
    'Technology Operations Manager',
    'Storage Architect', 'Storage Engineer',
    'Backup Administrator', 'Backup Engineer',
    'CISO', 'Chief Information Security Officer',
    'Security Architect', 'Security Engineer',
    'Information Security Manager'
  ],
  persona_seniority_levels = ARRAY['C-Level', 'VP', 'Director', 'Manager'],
  persona_departments = ARRAY[
    'Engineering',
    'IT',
    'Infrastructure',
    'Data Science',
    'Operations',
    'Security',
    'Cloud',
    'DevOps'
  ],
  persona_decision_roles = ARRAY[
    'Technical Decision Maker',
    'IT Decision Maker',
    'Business Decision Maker',
    'Infrastructure Decision Maker'
  ],
  tech_stack = ARRAY[
    'Wasabi',
    'Backblaze',
    'Cloudflare',
    'AWS S3',
    'Azure Blob Storage',
    'Google Cloud Storage',
    'Cloud Infrastructure',
    'Object Storage',
    'NAS Storage',
    'SAN Storage'
  ],
  intent_signals = ARRAY[
    'Cloud migration project',
    'Data center modernization',
    'Storage optimization initiative',
    'Infrastructure refresh',
    'Hybrid cloud deployment',
    'Multi-cloud strategy',
    'Data backup strategy',
    'Disaster recovery planning'
  ],
  buying_triggers = ARRAY[
    'Infrastructure modernization',
    'Cloud transformation',
    'Data management needs',
    'Storage capacity expansion',
    'Cost optimization',
    'Compliance requirements',
    'Data sovereignty concerns',
    'Performance improvement needs'
  ],
  budget_indicators = ARRAY[
    'IT budget increase',
    'Infrastructure investment',
    'Cloud spending growth',
    'Storage capacity expansion budget',
    'Digital transformation budget'
  ],
  pain_points = ARRAY[
    'High cloud storage costs',
    'Data management complexity',
    'Slow backup and recovery',
    'Limited storage scalability',
    'Vendor lock-in concerns',
    'Data sovereignty issues',
    'Performance bottlenecks',
    'Compliance challenges'
  ],
  confidence_score = 95,
  last_validated_at = now()
WHERE name = 'Enterprise Technology Companies' OR id = 'd5c7eca2-66f9-4dd3-995d-e26fb8c3fe1d';
